/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const LoginLazyImport = createFileRoute('/login')()
const AuthenticatedIndexLazyImport = createFileRoute('/_authenticated/')()
const AuthenticatedWarehouseIndexLazyImport = createFileRoute(
  '/_authenticated/warehouse/',
)()
const AuthenticatedProductIndexLazyImport = createFileRoute(
  '/_authenticated/product/',
)()
const AuthenticatedOrderIndexLazyImport = createFileRoute(
  '/_authenticated/order/',
)()
const AuthenticatedGoodsReceiptIndexLazyImport = createFileRoute(
  '/_authenticated/goods-receipt/',
)()
const AuthenticatedCustomerIndexLazyImport = createFileRoute(
  '/_authenticated/customer/',
)()
const AuthenticatedWarehouseCreateLazyImport = createFileRoute(
  '/_authenticated/warehouse/create',
)()
const AuthenticatedWarehouseIdLazyImport = createFileRoute(
  '/_authenticated/warehouse/$id',
)()
const AuthenticatedProductCreateLazyImport = createFileRoute(
  '/_authenticated/product/create',
)()
const AuthenticatedProductIdLazyImport = createFileRoute(
  '/_authenticated/product/$id',
)()
const AuthenticatedOrderCreateLazyImport = createFileRoute(
  '/_authenticated/order/create',
)()
const AuthenticatedGoodsReceiptCreateLazyImport = createFileRoute(
  '/_authenticated/goods-receipt/create',
)()
const AuthenticatedGoodsReceiptIdLazyImport = createFileRoute(
  '/_authenticated/goods-receipt/$id',
)()
const AuthenticatedCustomerCreateLazyImport = createFileRoute(
  '/_authenticated/customer/create',
)()
const AuthenticatedCustomerIdLazyImport = createFileRoute(
  '/_authenticated/customer/$id',
)()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AuthenticatedWarehouseIndexLazyRoute =
  AuthenticatedWarehouseIndexLazyImport.update({
    path: '/warehouse/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/warehouse/index.lazy').then((d) => d.Route),
  )

const AuthenticatedProductIndexLazyRoute =
  AuthenticatedProductIndexLazyImport.update({
    path: '/product/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product/index.lazy').then((d) => d.Route),
  )

const AuthenticatedOrderIndexLazyRoute =
  AuthenticatedOrderIndexLazyImport.update({
    path: '/order/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/order/index.lazy').then((d) => d.Route),
  )

const AuthenticatedGoodsReceiptIndexLazyRoute =
  AuthenticatedGoodsReceiptIndexLazyImport.update({
    path: '/goods-receipt/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/goods-receipt/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCustomerIndexLazyRoute =
  AuthenticatedCustomerIndexLazyImport.update({
    path: '/customer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customer/index.lazy').then((d) => d.Route),
  )

const AuthenticatedWarehouseCreateLazyRoute =
  AuthenticatedWarehouseCreateLazyImport.update({
    path: '/warehouse/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/warehouse/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedWarehouseIdLazyRoute =
  AuthenticatedWarehouseIdLazyImport.update({
    path: '/warehouse/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/warehouse/$id.lazy').then((d) => d.Route),
  )

const AuthenticatedProductCreateLazyRoute =
  AuthenticatedProductCreateLazyImport.update({
    path: '/product/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product/create.lazy').then((d) => d.Route),
  )

const AuthenticatedProductIdLazyRoute = AuthenticatedProductIdLazyImport.update(
  {
    path: '/product/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/product/$id.lazy').then((d) => d.Route),
)

const AuthenticatedOrderCreateLazyRoute =
  AuthenticatedOrderCreateLazyImport.update({
    path: '/order/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/order/create.lazy').then((d) => d.Route),
  )

const AuthenticatedGoodsReceiptCreateLazyRoute =
  AuthenticatedGoodsReceiptCreateLazyImport.update({
    path: '/goods-receipt/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/goods-receipt/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedGoodsReceiptIdLazyRoute =
  AuthenticatedGoodsReceiptIdLazyImport.update({
    path: '/goods-receipt/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/goods-receipt/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCustomerCreateLazyRoute =
  AuthenticatedCustomerCreateLazyImport.update({
    path: '/customer/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customer/create.lazy').then((d) => d.Route),
  )

const AuthenticatedCustomerIdLazyRoute =
  AuthenticatedCustomerIdLazyImport.update({
    path: '/customer/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customer/$id.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/customer/$id': {
      preLoaderRoute: typeof AuthenticatedCustomerIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/customer/create': {
      preLoaderRoute: typeof AuthenticatedCustomerCreateLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/goods-receipt/$id': {
      preLoaderRoute: typeof AuthenticatedGoodsReceiptIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/goods-receipt/create': {
      preLoaderRoute: typeof AuthenticatedGoodsReceiptCreateLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/order/create': {
      preLoaderRoute: typeof AuthenticatedOrderCreateLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/product/$id': {
      preLoaderRoute: typeof AuthenticatedProductIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/product/create': {
      preLoaderRoute: typeof AuthenticatedProductCreateLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/warehouse/$id': {
      preLoaderRoute: typeof AuthenticatedWarehouseIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/warehouse/create': {
      preLoaderRoute: typeof AuthenticatedWarehouseCreateLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/customer/': {
      preLoaderRoute: typeof AuthenticatedCustomerIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/goods-receipt/': {
      preLoaderRoute: typeof AuthenticatedGoodsReceiptIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/order/': {
      preLoaderRoute: typeof AuthenticatedOrderIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/product/': {
      preLoaderRoute: typeof AuthenticatedProductIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/warehouse/': {
      preLoaderRoute: typeof AuthenticatedWarehouseIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedIndexLazyRoute,
    AuthenticatedCustomerIdLazyRoute,
    AuthenticatedCustomerCreateLazyRoute,
    AuthenticatedGoodsReceiptIdLazyRoute,
    AuthenticatedGoodsReceiptCreateLazyRoute,
    AuthenticatedOrderCreateLazyRoute,
    AuthenticatedProductIdLazyRoute,
    AuthenticatedProductCreateLazyRoute,
    AuthenticatedWarehouseIdLazyRoute,
    AuthenticatedWarehouseCreateLazyRoute,
    AuthenticatedCustomerIndexLazyRoute,
    AuthenticatedGoodsReceiptIndexLazyRoute,
    AuthenticatedOrderIndexLazyRoute,
    AuthenticatedProductIndexLazyRoute,
    AuthenticatedWarehouseIndexLazyRoute,
  ]),
  LoginLazyRoute,
  RegisterLazyRoute,
])

/* prettier-ignore-end */
